- hosts: all
  become: yes
  become_user: root
  vars:
    mynfs: "192.168.1.225:/tank/pishare"
    mountpoint: "/mnt/pishare"
    permission: '0777'
    myopts: 'rw,sync'
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Install NFS tools
      ansible.builtin.apt:
        name:
          - nfs-common
          - nfs4-acl-tools
        state: present

    - name: check mountpoint exist
      ansible.builtin.file:
        path: "{{ mountpoint }}"
        state: directory
        mode: "{{ permission }}"
        owner: root
        group: root

    - name: mount network share
      ansible.posix.mount:
        src: "{{ mynfs }}"
        path: "{{ mountpoint }}"
        fstype: nfs
        opts: "{{ myopts }}"
        state: mounted

    - name: Install Raspberry Pi packages
      ansible.builtin.apt:
        name:
          - linux-modules-extra-raspi
        state: present